# -*- coding: utf-8 -*-
"""Training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1txDxmZ6cxhC835lErwq0UxRyvsNsFFto
"""

# Install ESRGAN dependencies : Python 3, PyTorch>=1.0, CUDA>=7.5, OpenCV

!pip install torch torchvision

!nvidia-smi

!pip install numpy opencv-python

import torch
import numpy as np
import cv2

print("PyTorch Version:", torch.__version__)
print("CUDA Available:", torch.cuda.is_available())
print("NumPy Version:", np.__version__)
print("OpenCV Version:", cv2.__version__)

!git clone https://github.com/xinntao/ESRGAN

!cd ESRGAN

"""pretrained model "RRDB_ESRGAN_x4.pth" uploaded to ./ESRGAN/models

Added to LR :

test-before/frame0.jpg  

test-before/frame40.jpg

test-before/frame77.jpg

(chose 3 images randomly, to make it quicker and due to insufficient gpu)
"""

!python ESRGAN/test.py

