# -*- coding: utf-8 -*-
"""ESRGAN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1txDxmZ6cxhC835lErwq0UxRyvsNsFFto
"""

# Install ESRGAN dependencies : Python 3, PyTorch>=1.0, CUDA>=7.5, OpenCV

!pip install torch torchvision

!nvidia-smi

!pip install numpy opencv-python

import torch
import numpy as np
import cv2

print("PyTorch Version:", torch.__version__)
print("CUDA Available:", torch.cuda.is_available())
print("NumPy Version:", np.__version__)
print("OpenCV Version:", cv2.__version__)

!git clone https://github.com/xinntao/ESRGAN

!cd ESRGAN

#pretrained model "RRDB_ESRGAN_x4.pth" uploaded to ./ESRGAN/models

#Added to LR :

#test-before/frame0.jpg

#test-before/frame40.jpg

#test-before/frame77.jpg

#(chose 3 images randomly, to make it quicker and due to insufficient gpu)

!python ESRGAN/test.py

#How to train an Real-ESRGAN Compact(SRVGGNet) model

#upload dependencies : python, pytorch, git clones

!git clone https://github.com/xinntao/Real-ESRGAN.git
!cd Real-ESRGAN

!git clone https://github.com/xinntao/BasicSR

# Install basicsr - https://github.com/xinntao/BasicSR
# We use BasicSR for both training and inference
!pip install basicsr
# facexlib and gfpgan are for face enhancement
!pip install facexlib
!pip install gfpgan
!python setup.py develop

#upload mri video data frame by frame to colab

!pip install -r Real-ESRGAN/requirements.txt

from google.colab import files

# Upload one or more files
uploaded = files.upload()

# List the uploaded files
for filename in uploaded.keys():
    print(f'Uploaded file: {filename}')

#meta info txt creator

import os

# Directory containing your files
directory = "./"

# Output file name
output_file = "Real-ESRGAN/meta_info.txt"

# Get a list of file paths in the directory
file_paths = [os.path.join(directory, filename) for filename in os.listdir(directory) if os.path.isfile(os.path.join(directory, filename))]

# Write the file paths to the output file
with open(output_file, 'w') as file:
    for path in file_paths:
        file.write(path + '\n')

print(f"Meta information written to {output_file}")

!pip install realesrgan

#train command

!python3 Real-ESRGAN/realesrgan/train.py -opt Real-ESRGAN/options/mri-wyw-model.yml --auto_resume

#connect to drive to save the created files
from google.colab import drive
drive.mount('/content/drive')

#create a backup file in drive
!mkdir -p '/content/drive/MyDrive/RealESRGAN_backup'

!pwd
!ls

#upload backup to drive
!cp -r '/content/Real-ESRGAN' '/content/drive/MyDrive/RealESRGAN_backup'

#double check
!ls '/content/drive/MyDrive/RealESRGAN_backup'